### ISSUE TITLE
Errors

### ISSUE THREAD

**Issue by kikohs** [NicholasMolyneaux/data-viz#3]
Hi, the viz is unstable. It worked the first time but now I cannot load the 3D or 2D map.
![screen shot 2018-12-26 at 16 22 35](https://user-images.githubusercontent.com/1793640/50449915-aa2f1700-092a-11e9-9ebf-4cb4e4919e8d.png)

Please fix ASAP.

Thank you

**Comment by glederrey** [comment]
The backend has been restarted. Sometimes, it crashes and we haven't figured out why. Sprry about that.
